version: '3'
services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    integration-test:
        build: .
        environment:
            - DOCKER_TEST=true
        command: "npm test"
        links:
            - mongodb
        depends_on:
            - mongodb