version: '3'
services:
    redisdb:
        image: redis:latest
        command: redis-server --logfile /dev/null # --quiet
        volumes:
            - redisdb-data:/data
        ports:
            - 6379
    mongodb:
        image: mongo:latest
        volumes:
            - mongodb-data:/data/db
        ports:
            - 27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    spacecom-api:
        build: .
        environment:
            - REDIS_DB_URL=redis://redisdb
            - MONGO_DB_URI=mongodb://mongodb/spacecom
            - SOURCE_FILE_PATH=./gates.txt
            - API_PORT=${API_PORT:-3000}
        command: npm start
        ports:
            - ${API_PORT:-3000}:${API_PORT:-3000}
        links:
            - mongodb
            - redisdb
        depends_on:
            - mongodb
            - redisdb

volumes:
  mongodb-data:
  redisdb-data:
